### ISSUE TITLE
Good First Issues

### ISSUE THREAD

**Issue by bitkarrot** [HiveTalk/zaplist#2]
see https://github.com/HiveTalk/zaplist/blob/main/README.md#good-first-issues-todo-items

**Comment by TheWildHustle** [comment]
I've created pull requests for the five issues in "Good First Issues #2" 

I'll group all the changes into one big pull request for your review.

Still having problems using the service with my npub, Ha!

I'll hop back into it and submit an issue request if the problem persists.

**Comment by bitkarrot** [comment]
OK!  Sounds good. I will wait for your consolidation, thanks for working on this.   Did you try changing the relays for your npub? Some of the larger relays will block if you have too many simulanteous requests.
